### ISSUE TITLE
Swift 2.3 and 3.0 updates

### ISSUE THREAD

**Issue by siavashalipour** [ReactiveKit/Bond#269]
I was just wondering if anyone currently working on migrating the repo to Swift 2.3 and 3.0 ?

**Comment by srdanrasic** [comment]
Yes, work is in progress! :) There will be Bond 5 with Swift 3 support. You can expect some breaking changes both because Swift is changing and I'm doing a refactoring that will improve performance and simplify the library.

You can expect beta in one or two weeks. Final version will be ready with Xcode 8 GM.

**Comment by siavashalipour** [comment]
Thanks @srdanrasic . I have already migrated my project to 3.0 and made the changes to the Bond (although nothing very specific just made it compile with 3.0). Just also wanted to thank you for this amazing pod. I am really enjoying using it.

**Comment by bytegh** [comment]
Hey @srdanrasic  is there any branch support swift2.3? I want to use in that version. thanks

**Comment by srdanrasic** [comment]
Currently all effort is on Swift 3. But it should be simple to fork the repo and run migrator to 2.3.

**Comment by bytegh** [comment]
Got it! Trying to do that. thanks @srdanrasic

**Comment by tadasz** [comment]
Is there anything I could help with migration to 3.0? When are you planning to have a working version?

**Comment by srdanrasic** [comment]
Hi @tadasz, Beta 1 is already released. I think we are there 100% feature-wise. I'd just like to have more unit testing before releasing non-beta. 

Hopefully it won't take longer than a week. If you're up for some unit testing, it would be great :)

**Comment by Broich** [comment]
@srdanrasic currently ReactiveKit throws an error in `SignalProtocol.swift` when compiled as a dependency of Bond5 with the latest Xcode 8 release. Any recommended workaround?

**Comment by srdanrasic** [comment]
Ah, the latest release. I'll have it fixed today.

**Comment by srdanrasic** [comment]
Hi @Broich, I've just released v5.0.0-beta3. I hope it will work now.

**Comment by Broich** [comment]
Thanks so much! 👍

Just another short question - with Bond5 there is no more access to the containing array of `ObservableArray` - what's the recommended way to e.g. exchange objects within a `MutableObservableArray`?

**Comment by patrick-lind** [comment]
Maybe it's just me but when I pull down the master branch and try to compile in Xcode 8 I get the following error messages:

Swift Compiler Error Group
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.0.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIKit.h:8:9: 'UIKit/UIKitDefines.h' file not found
Could not build Objective-C module 'UIKit'

Anyone else seeing this?

**Comment by srdanrasic** [comment]
Not sure if it's relevant, but make sure that you update git submodules if you are checking out the repo manually.

**Comment by patrick-lind** [comment]
I completely wiped out my Bond folder and downloaded from scratch from the newest master branch and still seeing the same thing. If I run 'git submodule update' nothing appears to happen and still get the same error messages. I will be transparent and mention that I'm not really familiar with working with Carthage and git submodules as well!

**Comment by srdanrasic** [comment]
If using carthage, you can do

```
carthage bootstrap
```

otherwise you can do

```
git submodule update --init
```

**Comment by patrick-lind** [comment]
Tried both of those options and seeing the same thing. Yes I am building through Xcode... Is that not the way to do it? Also for context, I was trying to figure out how to enable Swift Package Manager support and contribute back :)

**Comment by srdanrasic** [comment]
Yeah, that's the way to do it :) It's very strange. I just tried clean clone it it works normally for me.

Problem with SPM is that it is not integrated with Xcode so I wasn't even considering Bond supporting it at this time. How are you using SPM? Maybe I missed certain use cases.

**Comment by patrick-lind** [comment]
Well basically I'm trying to import your excellent Bond project into my project using SPM. So far the other dependencies I've used are supporting it: AlamoFire and etc. Also ReactiveKit, which you appear to depend on now is supporting it. I agree SPM is a little tedious at this point. You need to specify your Package.Swift file and then run "swift package generate-xcodeproj" and then it creates the Xcode project for you that has the dependencies plugged in appropriately.

**Comment by tlandsmancars** [comment]
I'm trying to convert my project with Swift 3 and I'm getting warnings "Result of call unused"

This happens even in the example given: 

    let name = Observable("Jim")
        name.observeNext { value in
            print("Hi \(value)!")
        }

How should we handle this?

**Comment by srdanrasic** [comment]
@tlandsmancars you need to dispose the returned disposable. Either put it in a dispose bag or save it in an non-named variable if you really don't need it.

```swift
let disposeBag = DisposeBag()
...
name.observeNext { value in
  print("Hi \(value)!")
}
```

or 

```swift
let _ = name.observeNext { value in
  print("Hi \(value)!")
}
```

to ignore it.

Please check out this: https://github.com/ReactiveKit/ReactiveKit#-cancellation

**Comment by srdanrasic** [comment]
Hi @patrick-lind, I just added Package.swift.

**Comment by patrick-lind** [comment]
Still trying to figure out my "Could not build Objective-C module 'UIKit'" issues. That said, I believe you may need to update some of the imports to get the SPM to work. When I run "swift build" on the repository I get the following error:

/Bond/Sources/AppKit/NSSegmentedControl.swift:34:35: error: use of undeclared type 'Bond'
  public var bnd_selectedSegment: Bond<NSSegmentedControl, Int> {
                                  ^~~~

**Comment by patrick-lind** [comment]
Sorry I was trying to fix it for you but still trying to figure out what's going on with my setup.

**Comment by tlandsmancars** [comment]
Thanks srdanrasic!  
One more quick question - what's the equivalent to observeNew?  I can't seem to get an equivalent working.

**Comment by chrisjb82** [comment]
Hi there, i've just updated to Xcode 8 and can't seem to get Bond to compile. The issue appears to be coming from ReactiveKit, any ideas? It's version 3.0.0-beta5

**Comment by srdanrasic** [comment]
Could you post more details about the issue? What exactly is failing?

**Comment by chrisjb82** [comment]
Line 437 of RawStream.swift (return distinct(areDistinct: !=)) is returning an error.
It would appear that there are two functions called distinct, one which takes no params and one which does. The compiler thinks it's trying to call the function which takes no params and throws a warning. 
This is happening with the GM build of XCode 8, when opening my project i have clicked the 'Update to Swift 3.0' button (after updating to 5.0.0-beta6).

**Comment by srdanrasic** [comment]
Hi @chrisjb82, there is something very wrong with your setup. RawStream.swift is no longer part of ReactiveKit. Are you using Carthage or CocoaPods?

**Comment by chrisjb82** [comment]
I'm using cocoapods, is carthage better? I completly erased the Pods/ folder and  then ran 'pod install', it bought down v3.0.0-beta5 but it looks like something else must be wrong. I also got a few compile issues in Bond, looks like they were to do with updates to parameter naming in swift 3, they maybe part of the same issue...

**Comment by patrick-lind** [comment]
CocoaPods vs Carthage appears to be the new tabs vs spaces argument. It's pretty much preference; each has their strong suits.

**Comment by chrisjb82** [comment]
Switching to Carthage seems to have fixed the issues i was seeing :)

**Comment by frogcjn** [comment]
Which version is compatible with Swift 2.3 and which version is compatible with Swift 3?

**Comment by Joebayld** [comment]
Trying to migrate my project to Bond5. Is it possible to access the original array in a `MutableObservableArray`? I use NSCoding and need to be able to serialize the data. See the following: 

`let data = NSKeyedArchiver.archivedData(withRootObject: model.testObjects.array)
`

**Comment by duanepfeiffer** [comment]
I just added Bond5 beta8 to an existing project but it doesn't seem to be ready for Swift 3.  I get hundreds of compiler errors after converting to swift 3.  What am I missing?  I'm using cocoa pods.

**Comment by srdanrasic** [comment]
Hi @duanepfeiffer, please see comments from chrisjb82. He had the same issue. It is something related to CocoaPods.

**Comment by chrisjb82** [comment]
@duanepfeiffer I had quite a few issues, needed to remove cocoa pods (old files left linked to workspace) and add via Carthage. One this is done you'll still have lots of issues to fix but they'll be in your code where you are using bond, this is mainly due to swift 3 syntax changes. if you look at the change log it should point you in the right direction, also note that you'll need to dispose of your binding else Xcode 8 will raise lots of warnings

**Comment by srdanrasic** [comment]
@chrisjb82, hmm, it's not required to dispose bindings, just observations (`observe`, `observeNext`). If Xcode is printing warnings to dispose bindings it is a bug.

**Comment by chrisjb82** [comment]
Apologies, i meant observations!

**Comment by Joebayld** [comment]
Hey @srdanrasic. What would your thoughts be on making the ObservableArray's array variable a public getter? That way it's possible to access the items for things like encoding the array. 

```
public class ObservableArray<Item>: Collection, SignalProtocol {
  
  public fileprivate(set) var array: [Item]
  fileprivate let subject = PublishSubject<ObservableArrayEvent<Item>, NoError>()
  fileprivate let lock = NSRecursiveLock(name: "ObservableArray")
```

**Comment by angadn** [comment]
Since I was heavily reliant on the old Bond in a framework-project, and hesitant to adding Obj-C bridging, have ported SwiftBond (4.3.1) to Swift 3.0 here in case it helps: https://github.com/angadn/bond

**Comment by i-schuetz** [comment]
@srdanrasic

RE: Disposables, couldn't the functions be annotated with `@discardableResult`?

**Comment by srdanrasic** [comment]
Observe functions are not annotated with `@discardableResult` because it's important to dispose the observations when you don't need them any more.

Only in rare cases you don't really care about disposals. In that case you can do

```swift
_ = signal.observe { ... }
```

or write your own overload of `observe*` methods that are annotated with `@discardableResult`.

**Comment by i-schuetz** [comment]
Thanks for the quick reply!

Why is it important to dispose the observations?

I use these functions only to pass a callback to handle the events, never cared about the result of observe. Is this wrong?

**Comment by a-rodriguez296** [comment]
@tlandsmancars @srdanrasic  did you ever get a response for your question regarding observeNew?

**Comment by obuseme** [comment]
FYI in case anyone missed it, Xcode 8.2 will be the last version that supports Swift 2.3.  Apple suggests migrating projects to Swift 3.

https://developer.apple.com/library/prerelease/content/releasenotes/DeveloperTools/RN-Xcode/Introduction.html

I'm anxiously awaiting a Bond release compatible with Swift 3.

**Comment by poseidonsw** [comment]
Any word on how to fix the issue with installing using cocoapods? I really don't want to change over carthage for this project now.

**Comment by srdanrasic** [comment]
What issue? Are you using latest CocoaPods?

**Comment by tonyarnold** [comment]
Bond v5.x is compatible with Swift 3, and was released just under a month ago. I think the original issue posed here is addressed — please open new issues if you're having specific problems with the latest release of Bond. Thanks!

**Comment by KarthikV710** [comment]
@srdanrasic What is the equivalent for observeNew?

**Comment by srdanrasic** [comment]
@KarthikV710 `skip(1).observeNext {}`

**Comment by KarthikV710** [comment]
Thanks a lot @srdanrasic . Appreciate your help :)
